#!/usr/bin/env perl

use strict;
use warnings;

use File::Find;

my $dir = shift @ARGV;
usage() if not $dir or not -d $dir;


find({
    wanted   => \&match,
    no_chdir => 1,
}, shift @ARGV );

sub match {
    return if -d or not /\.pm$/;
    my $orig = $_;

    s/lib\///;
    symlink $orig, join "::", split /\//;
}

sub usage {
    print( "no.\n" );
    exit;
}
